queue_rules:
  - merge_method: fast-forward
    autoqueue: true
    name: merge queue
    queue_conditions:
      - or:
          - and:
              - "#approved-reviews-by >= 1"
              - "#changes-requested-reviews-by = 0"
          - label = ready-to-merge
merge_protections_settings:
  post_comment: false
pull_request_rules:
  - name: Add label when review needed
    conditions:
      - or:
          - "#approved-reviews-by = 0"
          - "#changes-requested-reviews-by = 0"
      - label != ready-to-merge
      - -closed
      - -draft
    actions:
      label:
        toggle:
          - needs-review
  - name: Remove ready-to-merge label after merge/close
    conditions:
      - closed
    actions:
      label:
        remove:
          - ready-to-merge
merge_protections:
  - name: One review or merge label
    description: PR should either have one approved review or the ready-to-merge label
    if:
      - base = master
    success_conditions:
      - or:
          - -closed
          - label = ready-to-merge
          - "#approved-reviews-by >= 1"
