queue_rules:
  - merge_method: fast-forward
    autoqueue: true
    name: merge queue
    queue_conditions:
      - base = master
      - or:
          - and:
              - "#approved-reviews-by >= 1"
              - "#changes-requested-reviews-by = 0"
          - label = skip-review
    branch_protection_injection_mode: merge
merge_protections_settings:
  post_comment: false
pull_request_rules:
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
  - name: Add label when review needed
    conditions:
      - or:
          - "#approved-reviews-by = 0"
          - "#changes-requested-reviews-by = 0"
      - label != skip-review
      - -closed
      - -draft
    actions:
      label:
        toggle:
          - needs-review
  - name: Remove skip-review label after merge/close
    conditions:
      - closed
    actions:
      label:
        remove:
          - skip-review
merge_protections:
  - name: One review or merge label
    description: PR should either have one approved review or the skip-review label
    if:
      - base = master
    success_conditions:
      - or:
          - closed
          - label = skip-review
          - "#approved-reviews-by >= 1"
