queue_rules:
  - merge_method: fast-forward
    autoqueue: true
    name: merge queue
    queue_conditions:
      - or:
          - and:
              - "#approved-reviews-by >= 1"
              - "#changes-requested-reviews-by = 0"
          - label = ready-to-merge
merge_protections_settings:
  post_comment: false
