queue_rules:
  - merge_method: fast-forward
    autoqueue: true
    name: merge queue
    queue_conditions:
      - or:
          - changes-requested-reviews-by = 0
          - approved-reviews-by >= 1
          - label = ready-to-merge
    branch_protection_injection_mode: none
merge_protections_settings:
  post_comment: false
