name: Release

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      artifact-id:
        description: The artifact ID to download
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, linux]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ inputs.artifact-id }}

      - uses: actions/setup-dotnet@v5
        name: Install .NET
        with:
          dotnet-version: v8.0.x

      - name: Get version
        id: nbgv
        uses: dotnet/nbgv@master

      - name: Create release
        env:
          PLATFORM: ${{ matrix.platform }}
          VERSION: ${{ steps.nbgv.outputs.SemVer2 }}
          REPO_URL: https://github.com/${{ github.repository }}
          PACK_ID: NDC.StreamOverlay
          APP_NAME: NDC Stream Overlay
          APP_AUTHORS: NDC Tourney
          EXECUTABLE: ndc-stream-overlay${{ matrix.platform == 'win' && '.exe' }}
          TAG: v${{ steps.nbgv.outputs.SemVer2 }}
          COMMITISH: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet tool install -g vpk
          vpk download github --repoUrl $REPO_URL -c $PLATFORM
          vpk [$PLATFORM] pack -u $PACK_ID -v $VERSION -p $PLATFORM -e $EXECUTABLE
          vpk upload github --repoUrl $REPO_URL --publish --tag $TAG --targetCommitish $COMMITISH --merge --token $TOKEN -c $PLATFORM
